language: node_js
node_js:
  - "node"
before_install:
  - npm install -g npm@latest
  - npm --version
  - npm install -g rimraf babel-cli jest-cli node-sass eslint webpack
install:
  - npm install
script:
  - npm test
  - npm run report-coverage